zookeeper.connectString: 192.168.0.5:2181

server:
  port: 9023

spring.jpa:
    show-sql: true
    database: MYSQL
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

spring.datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.5:3306/cmd_send?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: vortex
    password: vortex2016


spring.redis:
    host: 192.168.0.5
    port: 6379
    password: vortex2016

spring:
  output:
    ansi:
      enabled: ALWAYS



