zookeeper.connectString: 10.26.250.162:2181

das:
  nodeId: TRCAN_1
  host: localhost
  port: 20001


spring.redis:
    host: 8a8b8cf47fdd4476.redis.rds.aliyuncs.com
    port: 6379
    password: vorTex2016