###############################################################
#                 自定义配置项
###############################################################
zookeeper.connectString: 127.0.0.1:2181

spring.redis:
    host: 127.0.0.1
    port: 6379
    password: tf56iot

spring.datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dms?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: tf56iot
    password: 123456

iot.rocketmq.brokers: localhost:10911