###############################################################
#                 自定义配置项
###############################################################
zookeeper.connectString: ${${spring.profiles.active:default}-zookeeperServer}:2181

spring.boot.admin.url: http://ops-monitor:8989
logServer:  elk-logstash

spring.redis:
    host: ${${spring.profiles.active:default}-redisServer}
    port: 6379
    password: vortex2016


spring.datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${${spring.profiles.active:default}-mysqlServer}/dms?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: vortex
    password: vortex2016

eureka:
  client:
    service-url:
      defaultZone: http://ops-discovery:${eureka.port:8761}/eureka/
