###############################################################
#                 自定义配置项
###############################################################
zookeeper.connectString: mt-zookeeper-vip:2181


spring.redis:
    host: localhost
    port: 6379
    password: tf56iot


spring.datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///dms?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: vortex
    password: vortex2016

iot.rocketmq.brokers: localhost:10911
