zookeeper.connectString: localhost:2181

das:
  nodeId: TRCAN_1
  host: localhost
  port: 20001


spring.redis:
    host: localhost
    port: 6379
    password: vortex2016


spring:
  output:
    ansi:
      enabled: ALWAYS




