zookeeper.connectString: 10.26.250.162:2181

server:
  port: 9023

spring.jpa:
    show-sql: true
    database: MYSQL
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

spring.datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp14v589k51e7m7j2.mysql.rds.aliyuncs.com:3306/dustbin_data?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: vortex
    password: vorTex2016


spring.redis:
    host: 8a8b8cf47fdd4476.redis.rds.aliyuncs.com
    port: 6379
    password: vorTex2016


spring:
  output:
    ansi:
      enabled: ALWAYS



