zookeeper.connectString: 192.168.1.30:2181

das:
  nodeId: TRCAN_1
  host: localhost
  port: 20001


spring.redis:
    host: 192.168.1.30
    port: 6379
    password: vortex2016


spring:
  output:
    ansi:
      enabled: ALWAYS




